# Install a role from a specific git branch
- name: docker-role
  scm: git
  src: git@github.com:polinchw/docker-role.git
  version: master
- name: rancher-role
  scm: git
  src: git@github.com:polinchw/rancher-role.git
  version: master  