---
# tasks file for rancher-role
- include_tasks: install-docker.yml
  args:
    apply:
      become: yes
      become_user: root
  tags: docker
- name: Clone rancher docker-compose
  git:
    repo: "https://github.com/polinchw/{{ repo_name }}.git"
    dest: "/home/{{ ansible_user_id }}/{{ repo_name }}/"
    clone: yes
    update: yes
  tags: rancher
- name: docker-compose up
  command: docker-compose up -d
  args:
    chdir: "/home/{{ ansible_user_id }}/{{ repo_name }}"
  tags: rancher